pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/mahii47/NaukariProfile'
            }
        }
        stage('Build') {
            steps {
                bat 'mvn clean compile'
            }
        }
        stage('Run Tests') {
            steps {
                bat 'mvn test'
            }
        }
    }
}
